### ISSUE TITLE
Error in console if 5 jobs not found

### ISSUE THREAD

**Issue by zrowe** [zrowe/WorthIt#24]
When selecting certain jobs, the console shows an error.  The jobs are:

Data Scientist
DevOps
Front End
QA engineer

The error is:

jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'url' of undefined TypeError: Cannot read property 'url' of undefined
    at Object.<anonymous> (https://zrowe.github.io/WorthIt/assets/javascript/jobsearch.js:25:32)
    at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined

looks like it is coming from here:

https://github.com/zrowe/WorthIt/blob/master/assets/javascript/jobsearch.js#L25

**Comment by rmglennon** [comment]
good detective work. I've been trying to track down the cause of this.
